### ISSUE TITLE
FluidNC 6XCNC Controller - strange LED lights and steppers suddenly not working

### ISSUE THREAD

**Issue by shenzhenadam** [breiler/fluid-installer#10]
Hello, I have a new issue with the FluidNC 6XCNC Controller. While yesterday I did my first test run on the wood plank: https://youtu.be/z4_9rOci9T8?si=AOMqgIGy_-KCQBn9 - and everything went well ...
And today I was about to start a new job, but nothing worked correctly - The Z axis did not move, the Y axis would move but the two steppers not in sync, and the X axis would move - but I was not able to home any of the axis. Also the LEDs were not lighting up correctly.  I have not touched anything since that job yesterday.

I am using UGS via USB cable and I am not using the FluidNC WebUI 

I have since detached the controller from the steppers and machine and have again clean installed the latest firmware and uploaded the most recent 6x_default.yaml from github to see if my custom yaml was corrupted somehow overnight. And then testing again to see what happens with the lights - it looks strange still: see image & video here: https://imgur.com/a/fluidnc-6xcnc-contoller-issue-iXHO72h
Is this a component failure or something in the firmware corrupted? I am getting no error codes. Is there something I can do by terminal to see what's going on - any other suggestion please. 

Please see attached yaml file I was using yesterday which worked fine with my machine.

Many thanks!

[6x_default-adam-XYYZ.txt](https://github.com/breiler/fluid-installer/files/15310977/6x_default-adam-XYYZ.txt)

**Comment by breiler** [comment]
Please create the issue over at https://github.com/bdring/FluidNC/.
