### ISSUE TITLE
Wi-Fi APs sorted wrong order

### ISSUE THREAD

**Issue by filimonic** [breiler/fluid-installer#14]
Wi-Fi APs sorted wrong order.
Better if it will be sorted descending by signal strength
![image](https://github.com/user-attachments/assets/8820cc1b-e09d-4144-b770-6f8273dfffa4)

**Comment by breiler** [comment]
Thanks for the feedback, fixed in:
https://github.com/breiler/fluid-installer/commit/4972435b7619ceac8ac73e1405c8225983e7a7a0
