### ISSUE TITLE
File upload not working as before.

### ISSUE THREAD

**Issue by V1EngineeringInc** [breiler/fluid-installer#6]
Something changed recently. Maybe in the last week or so. Some of my boards will not load the file transfer panel even after a reboot. (I have fixed it on my new boards). 

Seems like some sort of reboot timing or something.

It previously worked just fine, and I see there have been a couple recent merges.

**Comment by breiler** [comment]
Sorry about the late response, did not get an email notification.

It could be this commit that is causing it:
https://github.com/breiler/fluid-installer/commit/c9a59ce6c5a6d4dde70837a13ce7e18eed66a401

I noticed that on Windows it wouldn't connect properly if I had connected to the controller previously from a sender and this fixed that. I'll have to investigate...

**Comment by V1EngineeringInc** [comment]
Thanks!

We made some changes to the jackpot boards and they now have a more robust boot sequence and they seem fine, in the previous version boards I have to take the ESP32's off to use your file upload tool.

It would be great if you could revert or fix that part without killing whatever feature that brought in, but if you can't, it is not the end of the world.

**Comment by breiler** [comment]
Ok, I removed the restart in the beginning of the connection, and I can't reproduce my original issue that needed this fix.

Give it a try now.

**Comment by V1EngineeringInc** [comment]
Awesome!!! Back to working perfectly. Thanks, The web tool makes flashing a bunch of boards real smooth.
