### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by justinclift** [breiler/fluid-installer#7]
If there any chance this will support Firefox in the near-ish future?

Asking because at present it just displays a warning instead:

```
Browser not supported
Please use Chrome, Edge or Opera instead
```

**Comment by breiler** [comment]
The browser API:s that we currently rely on are still considered experimental:
https://developer.mozilla.org/en-US/docs/Web/API/Web_Serial_API

When these features are available in Firefox we can add it.

**Comment by justinclift** [comment]
Ahhh, interesting approach.  No worries. :wink:

**Comment by justinclift** [comment]
Oops, forgot to close this.  Doing so now. :smile:
